### ISSUE TITLE
в виде кода не может войти по токену

### ISSUE THREAD

**Issue by firs-iln** [mewforest/vk-music-import#12]
**Опишите проблему**
код не может получить доступ к странице, падает из-за несовпадения ip, не совсем понятно как это возможно, учитывая, что получение токена и запуск проекта происходят на одной машине

**Как воспроизвести ошибку**
запуск через cmd, следую инструкциям

 - Windows 11
 - VK_TOKEN="токен"
BYPASS_CAPTCHA="1"
SPOTIFY_MODE="0"
REVERSE="0"
STRICT_SEARCH="1"
ADD_TO_LIBRARY="1"
 - добавление из треклиста
 - vk.com/firs_iln
 - python
 - 3.0

**Дополнительная информация**
ERROR:root:[5] User authorization failed: access_token was given to another ip address.
Traceback (most recent call last):
  File "D:\Загрузки\vk-music-import-0.3\vk-music-import-0.3\vk-music-import.py", line 140, in main
    user_info = vk.users.get()[0]
  File "C:\Users\firs_\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vk_api\vk_api.py", line 737, in __call__
    return self._vk.method(self._method, kwargs)
  File "C:\Users\firs_\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [5] User authorization failed: access_token was given to another ip address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Загрузки\vk-music-import-0.3\vk-music-import-0.3\vk-music-import.py", line 364, in <module>
    main()
  File "D:\Загрузки\vk-music-import-0.3\vk-music-import-0.3\vk-music-import.py", line 145, in main
    user_info = vk.users.get()[0]
  File "C:\Users\firs_\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vk_api\vk_api.py", line 737, in __call__
    return self._vk.method(self._method, kwargs)
  File "C:\Users\firs_\AppData\Local\Programs\Python\Python38-32\lib\site-packages\vk_api\vk_api.py", line 697, in method
    raise error
vk_api.exceptions.ApiError: [5] User authorization failed: access_token was given to another ip address.
Нажмите Enter, чтобы завершить работу программы...

**Comment by mewforest** [comment]
Скорей всего токен был получен на другой IP-адрес. Попробуйте выключить VPN и заменить содержимое `config.env` на [значения по умолчанию](https://github.com/mewforest/vk-music-import/blob/main/config.env).

Кстати, не забудьте проверить, что в самом браузере также не включен VPN/прокси.
